import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth } from 'firebase/auth';

// We use environment variables for production/GitHub to avoid exposing secrets.
// The firebase-applet-config.json is now ignored by git.
let firebaseConfig: any;

try {
  // Try to load from environment variables first (Vite style)
  if (import.meta.env.VITE_FIREBASE_API_KEY) {
    firebaseConfig = {
      apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
      authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
      storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: import.meta.env.VITE_FIREBASE_APP_ID,
      firestoreDatabaseId: import.meta.env.VITE_FIREBASE_DATABASE_ID,
    };
  } else {
    // Fallback to the local config file generated by the platform
    // @ts-ignore - This file might not exist in some environments
    const config = await import('../../firebase-applet-config.json');
    firebaseConfig = config.default;
  }
} catch (e) {
  console.error("Firebase configuration missing. Please set environment variables or ensure firebase-applet-config.json exists.");
}

const app = initializeApp(firebaseConfig);
export const db = getFirestore(app, firebaseConfig?.firestoreDatabaseId);
export const auth = getAuth(app);
