import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth } from 'firebase/auth';

// We use environment variables for production/GitHub to avoid exposing secrets.
// The firebase-applet-config.json is now ignored by git.
let firebaseConfig: any = null;

// Try to load from environment variables first (Vite style)
if (import.meta.env.VITE_FIREBASE_API_KEY) {
  firebaseConfig = {
    apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
    authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
    projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
    storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
    appId: import.meta.env.VITE_FIREBASE_APP_ID,
    firestoreDatabaseId: import.meta.env.VITE_FIREBASE_DATABASE_ID,
  };
} else {
  try {
    // Fallback to the local config file generated by the platform
    // We use a dynamic import with a template literal to prevent Vite from failing at build time if the file is missing
    const configName = '../../firebase-applet-config.json';
    // @ts-ignore
    const config = await import(/* @vite-ignore */ configName);
    firebaseConfig = config.default;
  } catch (e) {
    console.warn("Firebase config file not found. This is expected if you haven't set up Firebase yet or are using environment variables.");
  }
}

// Initialize Firebase only if we have a config
const app = firebaseConfig ? initializeApp(firebaseConfig) : null;
export const db = app ? getFirestore(app, firebaseConfig?.firestoreDatabaseId) : null;
export const auth = app ? getAuth(app) : null;
