import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth } from 'firebase/auth';

// We use environment variables for production/GitHub to avoid exposing secrets.
// The firebase-applet-config.json is now ignored by git.
let firebaseConfig: any = null;

// Try to load from environment variables first (Vite style)
if (import.meta.env.VITE_FIREBASE_API_KEY) {
  console.log("Firebase: Loading config from environment variables.");
  firebaseConfig = {
    apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
    authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
    projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
    storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
    appId: import.meta.env.VITE_FIREBASE_APP_ID,
    firestoreDatabaseId: import.meta.env.VITE_FIREBASE_DATABASE_ID || '(default)',
  };
} else if (import.meta.env.DEV) {
  try {
    console.log("Firebase: Attempting to load local config file.");
    // Fallback to the local config file generated by the platform (only in dev)
    const configName = '../../firebase-applet-config.json';
    // @ts-ignore
    const config = await import(/* @vite-ignore */ configName);
    firebaseConfig = config.default;
    console.log("Firebase: Local config loaded successfully.");
  } catch (e) {
    console.error("Firebase: Local config file NOT found. Please ensure firebase-applet-config.json exists in the root.");
  }
}

if (!firebaseConfig) {
  console.error("Firebase: No configuration found. Authentication and Database features will be disabled.");
}

// Initialize Firebase only if we have a config
const app = firebaseConfig ? initializeApp(firebaseConfig) : null;
export const db = app ? getFirestore(app, firebaseConfig?.firestoreDatabaseId || '(default)') : null;
export const auth = app ? getAuth(app) : null;
